import fs from "fs";
import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, WidthType, BorderStyle, PageNumber,
  Header, Footer, PageBreak, TabStopPosition, TabStopType,
  UnderlineType,
} from "docx";

const BLUE = "08428C";
const DARK = "1F2937";
const MUTED = "6B7280";

function heading(level, text) {
  return new Paragraph({
    text,
    heading: level,
    spacing: { before: level === HeadingLevel.HEADING_1 ? 480 : 360, after: 200 },
  });
}

function para(text, opts = {}) {
  return new Paragraph({
    spacing: { after: 120, line: 276 },
    ...opts,
    children: [
      new TextRun({
        text,
        font: "Calibri",
        size: 22,
        color: DARK,
        ...(opts.bold ? { bold: true } : {}),
      }),
    ],
  });
}

function code(text) {
  return new Paragraph({
    spacing: { after: 80, line: 240 },
    indent: { left: 720 },
    children: [
      new TextRun({
        text,
        font: "Consolas",
        size: 18,
        color: "1E40AF",
      }),
    ],
  });
}

function spacer() {
  return new Paragraph({ spacing: { after: 120 }, children: [] });
}

function bullet(text, level = 0) {
  return new Paragraph({
    spacing: { after: 60, line: 260 },
    indent: { left: 360 + level * 360 },
    bullet: { level },
    children: [
      new TextRun({ text, font: "Calibri", size: 22, color: DARK }),
    ],
  });
}

function tableRow(cells, header = false) {
  return new TableRow({
    tableHeader: header,
    children: cells.map(c => new TableCell({
      width: { size: c.width || 25, type: WidthType.PERCENTAGE },
      children: [
        new Paragraph({
          spacing: { after: 40 },
          children: [
            new TextRun({
              text: c.text,
              font: "Calibri",
              size: 20,
              bold: header,
              color: header ? "FFFFFF" : DARK,
            }),
          ],
        }),
      ],
      shading: header ? { fill: BLUE } : c.shading ? { fill: c.shading } : undefined,
    })),
  });
}

function makeTable(headers, rows) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      tableRow(headers.map(h => ({ text: h, width: 100 / headers.length })), true),
      ...rows.map(row => tableRow(row.map((r, i) => ({ text: r, width: 100 / headers.length, shading: i % 2 === 0 ? "F9FAFB" : undefined })))),
    ],
  });
}

function multiPara(lines) {
  return lines.map(line => para(line));
}

async function main() {
  const doc = new Document({
    features: { updateFields: true },
    styles: {
      default: {
        document: { run: { font: "Calibri", size: 22, color: DARK } },
      },
    },

    sections: [
      {
        // ── Cover Page ──
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({ text: "AIPCA Bahati Cathedral — System Architecture", font: "Calibri", size: 16, color: MUTED, italics: true }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "Page ", font: "Calibri", size: 16, color: MUTED }),
                  new TextRun({ children: [PageNumber.CURRENT], font: "Calibri", size: 16, color: MUTED }),
                  new TextRun({ text: " of ", font: "Calibri", size: 16, color: MUTED }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], font: "Calibri", size: 16, color: MUTED }),
                ],
              }),
            ],
          }),
        },
        children: [
          new Paragraph({ spacing: { before: 3600 }, children: [] }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
            children: [
              new TextRun({ text: "AIPCA BAHATI CATHEDRAL", font: "Calibri", size: 36, bold: true, color: BLUE }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Harambee Development Fund", font: "Calibri", size: 28, color: BLUE }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: BLUE, space: 1 } },
            children: [],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
            children: [
              new TextRun({ text: "Complete System Architecture & Security Document", font: "Calibri", size: 32, bold: true, color: DARK }),
            ],
          }),
          new Paragraph({ spacing: { after: 400 }, children: [] }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Version 2.0 — June 2026", font: "Calibri", size: 22, color: MUTED }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Classification: Confidential", font: "Calibri", size: 20, color: "DC2626", bold: true }),
            ],
          }),
          new Paragraph({ spacing: { before: 3600 }, children: [] }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Prepared for: Harambee Committee & Church Board", font: "Calibri", size: 20, color: MUTED }),
            ],
          }),
        ],
      },
      {
        // ── Table of Contents ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "Table of Contents"),
          spacer(),
          ...[
            "1. Executive Summary",
            "2. System Overview & Architecture Diagram",
            "3. Technology Stack",
            "4. Frontend Architecture",
            "5. Backend Architecture",
            "6. Database Schema & Data Flow",
            "7. Authentication & Authorization",
            "8. Security Architecture",
            "9. Integration Architecture",
            "10. Queue & Background Jobs",
            "11. Deployment Architecture",
            "12. Monitoring & Audit",
            "13. Incident Response & Recovery",
            "14. Appendices",
          ].map(t => para(t, { bold: true })),
        ],
      },
      {
        // ── 1. Executive Summary ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "1. Executive Summary"),
          para("The AIPCA Bahati Cathedral Harambee Management System is a full-stack web application designed to manage church fundraising, donations, pledges, member administration, and financial tracking for the Harambee Development Fund. The system processes mobile money transactions via M-Pesa, sends WhatsApp notifications via Meta Cloud API, and provides role-based administrative access with three tiers of permission."),
          para("The system serves a congregation of 900+ registered members across 11 fellowships, with a fundraising goal of KES 30,000,000 for the church building project. It processes an average of 50+ M-Pesa transactions daily and sends automated WhatsApp reminders for pledges and payment follow-ups."),
          para("Architecture: The system follows a modern JAMstack architecture with a React SPA frontend (Vite + TypeScript), Node.js/Express API running on Vercel Serverless Functions, and Supabase (PostgreSQL) as the database. Background jobs are managed by BullMQ with Upstash Redis."),
          para("Security posture: Defence-in-depth with JWT authentication (24h expiry), bcrypt password hashing (10 rounds), three-tier RBAC, per-IP rate limiting (300 req/min), session management, comprehensive audit logging, and data masking for restricted roles."),
        ],
      },
      {
        // ── 2. System Overview ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "2. System Overview & Architecture Diagram"),
          para("The system is composed of four main layers: Client (React SPA), API Layer (Express.js on Vercel Serverless), Integrations (Supabase, Redis, M-Pesa, Meta, AT), and External Services."),
          spacer(),
          para("ARCHITECTURE DIAGRAM (Text Representation)", { bold: true }),
          spacer(),
          code("┌─────────────────────────────────────────────────────────────────────────────┐"),
          code("│                         USERS / CLIENTS                                      │"),
          code("│  ┌──────────┐  ┌──────────┐  ┌──────────────┐  ┌───────────────────────┐   │"),
          code("│  │ Public   │  │ Donors   │  │ Admins       │  │ Super Admins          │   │"),
          code("│  │ (Browse) │  │ (M-Pesa) │  │ (Manage Data)│  │ (Full System Access)  │   │"),
          code("│  └────┬─────┘  └────┬─────┘  └──────┬───────┘  └──────────┬────────────┘   │"),
          code("└───────┼─────────────┼───────────────┼─────────────────────┼────────────────┘"),
          code("        │             │               │                     │                 "),
          code("        ▼             ▼               ▼                     ▼                  "),
          code("┌─────────────────────────────────────────────────────────────────────────────┐"),
          code("│                     CDN / VERCEL EDGE                                        │"),
          code("│  ┌───────────────────────────────────────────────────────────────────────┐  │"),
          code("│  │  Static Assets: index.html, JS bundle (1.4MB), CSS (91KB), images     │  │"),
          code("│  └───────────────────────────────────────────────────────────────────────┘  │"),
          code("└──────────────────────────────────┬──────────────────────────────────────────┘"),
          code("                                   │                                           "),
          code("                                   ▼                                           "),
          code("┌─────────────────────────────────────────────────────────────────────────────┐"),
          code("│                     API LAYER (Vercel Serverless Function)                   │"),
          code("│  ┌───────────────────────────────────────────────────────────────────────┐  │"),
          code("│  │  Express.js App — api/index.ts → server/index.ts                      │  │"),
          code("│  │  Middleware Stack: CORS → JSON Parser → Rate Limiter → Route Dispatch │  │"),
          code("│  │                                                                       │  │"),
          code("│  │  ┌────────┐ ┌──────────┐ ┌──────────┐ ┌────────────────┐             │  │"),
          code("│  │  │  Auth  │ │ require- │ │ require- │ │ require-       │             │  │"),
          code("│  │  │ Routes │ │ Admin    │ │ Super-   │ │ AdminOrAbove   │             │  │"),
          code("│  │  └───┬────┘ └────┬─────┘ └────┬─────┘ └───────┬────────┘             │  │"),
          code("│  │      │           │            │               │                       │  │"),
          code("│  │  ┌───▼───────────▼────────────▼───────────────▼────────────────────┐  │  │"),
          code("│  │  │              Route Handlers (18 modules)                        │  │  │"),
          code("│  │  │  auth │ admin │ members │ donations │ pledges │ mpesa │ c2b     │  │  │"),
          code("│  │  │  analytics │ settings │ fellowships │ ledger │ committee │ ...  │  │  │"),
          code("│  │  └─────────────────────────────────────────────────────────────────┘  │  │"),
          code("│  └───────────────────────────────────────────────────────────────────────┘  │"),
          code("└──────────────────────────────────┬──────────────────────────────────────────┘"),
          code("                                   │                                           "),
          code("                                   ▼                                           "),
          code("┌─────────────────────────────────────────────────────────────────────────────┐"),
          code("│                     INTEGRATIONS & DATA LAYER                                │"),
          code("│  ┌──────────┐  ┌──────────┐  ┌────────────┐  ┌───────────────┐             │"),
          code("│  │ Supabase │  │  Redis   │  │  M-Pesa    │  │  Meta Cloud   │             │"),
          code("│  │PostgreSQL│  │ (Cache/  │  │  Daraja    │  │  WhatsApp API │             │"),
          code("│  │  + RLS   │  │  Queue)  │  │  API       │  │  (Cloud API)  │             │"),
          code("│  └──────────┘  └──────────┘  └────────────┘  └───────────────┘             │"),
          code("│  ┌──────────┐  ┌──────────┐  ┌────────────┐  ┌───────────────┐             │"),
          code("│  │ Africa's │  │ Libre-   │  │  BullMQ    │  │  Twilio       │             │"),
          code("│  │ Talking  │  │ Translate│  │  Queue     │  │  (Deprecated) │             │"),
          code("│  │ (SMS)    │  │  (Free)  │  │  Workers   │  │               │             │"),
          code("│  └──────────┘  └──────────┘  └────────────┘  └───────────────┘             │"),
          code("└─────────────────────────────────────────────────────────────────────────────┘"),
          spacer(),
          para("Key architectural decisions:", { bold: true }),
          bullet("Serverless-first: All API logic runs on Vercel Serverless Functions (Node.js + Express), auto-scaling to zero when idle"),
          bullet("SPA architecture: React 19 with Vite 6, client-side routing via React Router, static hosting on Vercel Edge"),
          bullet("Supabase as backend-as-a-service: PostgreSQL database with Row-Level Security (RLS), real-time subscriptions, and managed auth"),
          bullet("BullMQ + Redis: Background job processing for reminders, M-Pesa polling, analytics cache refresh, and follow-up messages"),
          bullet("No ORM: Direct Supabase JS client queries for maximum control and performance"),
          bullet("Self-hosted LibreTranslate: Free Swahili auto-translation without external API costs"),
        ],
      },
      {
        // ── 3. Technology Stack ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "3. Technology Stack"),
          spacer(),
          makeTable(
            ["Layer", "Technology", "Version", "Purpose"],
            [
              ["Frontend Framework", "React", "19.x", "UI component library"],
              ["Build Tool", "Vite", "6.x", "Fast bundler and dev server"],
              ["Language", "TypeScript", "5.x", "Type-safe JavaScript"],
              ["Styling", "Tailwind CSS", "3.x", "Utility-first CSS framework"],
              ["Icons", "Lucide React", "Latest", "Vector icon library"],
              ["HTTP Client", "Native fetch", "Built-in", "API calls from browser"],
              ["Backend Runtime", "Node.js", "24.x", "Server-side JavaScript"],
              ["Backend Framework", "Express.js", "4.x", "HTTP server & routing"],
              ["Database", "Supabase (PostgreSQL)", "Latest", "Managed PostgreSQL + REST API"],
              ["Cache & Queue", "Upstash Redis", "Latest", "Serverless Redis for BullMQ and caching"],
              ["Auth", "jsonwebtoken", "9.x", "JWT signing and verification"],
              ["Password Hashing", "bcryptjs", "2.x", "Salt-based password hashing"],
              ["M-Pesa", "Safaricom Daraja API", "v2", "STK Push, C2B callbacks, status queries"],
              ["WhatsApp", "Meta Cloud API", "v21.0", "Business WhatsApp messaging"],
              ["SMS", "Africa's Talking", "Latest", "Password reset SMS (OTP)"],
              ["Translation", "LibreTranslate", "Self-hosted", "English to Swahili auto-translation"],
              ["Job Queue", "BullMQ", "5.x", "Redis-backed background job processing"],
              ["Document Generation", "PDFKit", "Latest", "PDF report generation"],
              ["Spreadsheet Export", "ExcelJS", "Latest", "Excel report generation"],
              ["Hosting", "Vercel", "Pro", "Static hosting + serverless functions"],
              ["Version Control", "GitHub", "Private", "Source code management"],
              ["SSL/TLS", "Cloudflare + Vercel", "Edge", "HTTPS termination"],
            ],
          ),
        ],
      },
      {
        // ── 4. Frontend Architecture ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "4. Frontend Architecture"),
          para("The frontend is a single-page application (SPA) built with React 19 and Vite 6, hosted on Vercel's static hosting with edge caching."),
          spacer(),
          heading(HeadingLevel.HEADING_2, "4.1 Page Structure"),
          spacer(),
          makeTable(
            ["Route", "Page Component", "Auth Required", "Description"],
            [
              ["/", "HomePage", "No", "Public landing page with hero, progress, fellowships, about, and pledge form"],
              ["/admin/login", "AdminLogin", "No", "Admin authentication with email + password"],
              ["/admin/setup", "AdminSetup", "First-time", "Initial super_admin account creation with phone number"],
              ["/admin/forgot-password", "ForgotPassword", "No", "Password reset request via WhatsApp OTP"],
              ["/admin/reset-password", "ResetPassword", "No", "Code entry + new password form with strength meter"],
              ["/admin/dashboard", "AdminDashboard", "Yes", "Full admin panel with 9 tabs"],
              ["/portfolio/:name", "JackPortfolio", "No", "Public donor portfolio showing personal giving history"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "4.2 Component Architecture"),
          para("The frontend uses a flat component structure under src/components/ with shared components for common UI patterns:"),
          spacer(),
          makeTable(
            ["Component", "Category", "Description"],
            [
              ["ChurchHero", "Public", "Landing hero section with church branding"],
              ["SlideshowBackground", "Public", "Rotating background images with overlays"],
              ["LiveProgress", "Public", "Real-time donation progress bar with auto-polling (30s)"],
              ["FellowshipProgress", "Public", "Per-fellowship donation bars sorted by performance"],
              ["AboutSection", "Public", "3D tilt cards with glassmorphism for church mission"],
              ["ContributeSection", "Public", "Pledge/donation CTA section"],
              ["PledgeBoard", "Public", "Animated pledge leaderboard with confetti"],
              ["DonationModal", "Public", "Modal with honour giving, M-Pesa STK Push"],
              ["DonationForm", "Public", "Inline donation form component"],
              ["Footer", "Public", "Church contact, social links, phone link"],
              ["jjack/JackRouter", "Public", "Portfolio route component"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "4.3 State Management"),
          para("The application uses React's built-in state management patterns:"),
          bullet("useState / useReducer: Local component state for forms, modals, and UI toggles"),
          bullet("useContext (LanguageContext): Global EN/SW language switching with localized strings"),
          bullet("localStorage: Persisted auth tokens, cached preferences, and content translations"),
          bullet("Optimistic updates: Admin dashboard mutations (edit/delete) update local state immediately, revert on server error"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "4.4 Key Frontend Features"),
          bullet("Responsive design: Mobile-first layout with bottom navigation bar on small screens"),
          bullet("Real-time polling: LiveProgress refreshes every 30 seconds; FellowshipProgress polls on mount"),
          bullet("Confetti + chime: Canvas-based celebration effect on donation submission"),
          bullet("Swahili/English bilingual: All static text available in both languages; dynamic content auto-translated"),
          bullet("Password strength meter: Real-time visual feedback on password security (ResetPassword, AdminSetup)"),
          bullet("Eye toggle on password fields: Show/hide password with Eye/EyeOff icons on all password inputs"),
          bullet("Confirm password validation: Real-time match check with green/red border indicators"),
        ],
      },
      {
        // ── 5. Backend Architecture ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "5. Backend Architecture"),
          para("The backend is a Node.js Express.js application running as a Vercel Serverless Function. It handles all API requests, business logic, authentication, and integration orchestration."),
          spacer(),
          heading(HeadingLevel.HEADING_2, "5.1 Route Modules (18)"),
          spacer(),
          makeTable(
            ["Route", "Module", "Mount Path", "Auth Required", "Key Endpoints"],
            [
              ["Auth", "auth.ts", "/api/auth", "Mixed", "login, setup, forgot-password, reset-password, sessions, logout"],
              ["Admin", "admin.ts", "/api/admin", "Yes", "stats, users CRUD, audit-logs, fellowship-report, migrate"],
              ["Members", "members.ts", "/api/members", "Mixed", "CRUD, bulk-add, bulk-edit, bulk-delete, dedup, search, member-list"],
              ["Donations", "donations.ts", "/api/donations", "Mixed", "CRUD with role-based filtering, masking"],
              ["Pledges", "pledges.ts", "/api/pledges", "Mixed", "CRUD, pay-with-mpesa, adjust, verify-phone, search"],
              ["M-Pesa", "mpesa.ts", "/api/mpesa", "Mixed", "stkpush, callback, status, query, resend-whatsapp"],
              ["C2B", "c2b.ts", "/api/c2b", "Public", "validation, confirmation callbacks from Safaricom"],
              ["Analytics", "analytics.ts", "/api/analytics", "Yes", "kpi, revenue chart, donations breakdown, pledges report"],
              ["Settings", "settings.ts", "/api/settings", "Mixed", "GET/PUT site settings, harambee date info"],
              ["Fellowships", "fellowships.ts", "/api/fellowships", "Mixed", "progress, goals, member stats"],
              ["Committee", "committee.ts", "/api/committee", "Yes", "CRUD operations"],
              ["Councils", "councils.ts", "/api/councils", "Mixed", "CRUD operations"],
              ["Campaigns", "campaigns.ts", "/api/campaigns", "Mixed", "CRUD operations"],
              ["Contributions", "contributions.ts", "/api/contributions", "Yes", "Excel/PDF export, reports"],
              ["Reminders", "reminders.ts", "/api/reminders", "Mixed", "send reminders, Bible verse, portfolio"],
              ["Ledger", "ledger.ts", "/api/ledger", "Yes", "Financial ledger"],
              ["Translate", "translate.ts", "/api/translate", "Public", "English to Swahili translation proxy"],
              ["Verses", "verses.ts", "/api/verses", "Public", "Bible verses for WhatsApp messages"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "5.2 Library Modules (8)"),
          spacer(),
          makeTable(
            ["Module", "File", "Key Exports", "Description"],
            [
              ["Auth/Middleware", "admin.ts", "requireAdmin, requireSuperAdmin, requireAdminOrAbove, logAudit, signToken, verifyToken, hashPassword, rateLimit", "JWT auth, RBAC middleware, audit logging, password utilities, rate limiting"],
              ["Supabase Client", "supabase.ts", "requireService, createClient (anon + service role)", "Dual Supabase client: service role with timeout for admin ops, anon for public"],
              ["Redis Client", "redis.ts", "getRedis, cacheGet, cacheSet, cacheKey", "Upstash Redis connection and caching utilities"],
              ["Queue", "queue.ts", "startAllWorkers, stopAllWorkers, enqueueReminder, enqueueFollowUp, enqueueMpesaPoll, enqueueAnalyticsRefresh", "BullMQ queue definitions and worker implementations"],
              ["Permissions", "permissions.ts", "hasPermission, requirePermission, DataType, Action", "Granular permission matrix for role-based access"],
              ["Audit", "audit.ts", "logAudit (v2)", "Type definitions and enhanced audit logging"],
              ["Meta WhatsApp", "meta-whatsapp.ts", "sendWhatsApp", "Meta Cloud API WhatsApp Business integration"],
              ["Africa's Talking", "africastalking.ts", "sendSMS, getSmsService", "AT SMS integration for password reset OTP"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "5.3 Middleware Stack"),
          para("The Express middleware executes in the following order for each request:"),
          spacer(),
          makeTable(
            ["Order", "Middleware", "Function", "Configuration"],
            [
              ["1", "CORS", "Permit cross-origin requests", "Credentials: true, Dynamic origin from env"],
              ["2", "JSON Body Parser", "Parse request body", "express.json()"],
              ["3", "Request ID", "Assign UUID to each request", "x-request-id header or crypto.randomUUID()"],
              ["4", "Rate Limiter", "Per-IP throttle", "300 requests/minute window"],
              ["5", "Route Dispatcher", "Match URL to route handler", "Express Router matching"],
              ["6", "requireAdmin", "JWT verification + admin context", "Bearer token → jwt.verify()"],
              ["7", "requireSuperAdmin", "Role check (super_admin only)", "admin.role === 'super_admin'"],
              ["8", "requireAdminOrAbove", "Role check (not viewer)", "admin.role !== 'viewer'"],
              ["9", "Route Handler", "Business logic execution", "Per-endpoint implementation"],
            ],
          ),
        ],
      },
      {
        // ── 6. Database Schema ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "6. Database Schema & Data Flow"),
          para("The database uses Supabase (PostgreSQL 15+) with 10+ tables. The service role key is used for server-side operations (bypassing RLS)."),
          spacer(),
          heading(HeadingLevel.HEADING_2, "6.1 Core Tables"),
          spacer(),
          makeTable(
            ["Table", "Key Columns", "Relationships", "Purpose"],
            [
              ["admin_users", "id, email, password_hash, role (super_admin|admin|viewer), phone, failed_attempts, locked_until", "Admin management"],
              ["church_members", "id, name, phone, council, gender, is_active, created_at", "council → councils.slug", "Member registry (900+)"],
              ["donations", "id, donor_name, amount, phone, status, method, receipt_number, church_member_id, honored_member_id, campaign_id, honour_known_as", "church_member_id → church_members.id, campaign_id → campaigns.id", "All donations (M-Pesa + manual)"],
              ["pledges", "id, donor_name, amount, paid, remaining, status (pending|fulfilled|cancelled), whatsapp_number, reminder_freq, campaign_id, rating, color_hex", "campaign_id → campaigns.id", "Pledge tracking with progress"],
              ["campaigns", "id, slug, title, description, goal, currency, is_active, starts_at, ends_at", "Fundraising campaigns"],
              ["councils", "slug, name, is_active, created_at", "Fellowships (11 records)"],
              ["settings", "key (PK), value", "Key-value site configuration"],
              ["audit_logs", "id, timestamp, actor_id, actor_name, actor_role, action, resource_type, resource_id, details, ip_address, user_agent, immutable", "Immutable audit trail"],
              ["sessions", "id, admin_id, token_hash, ip_address, user_agent, created_at, last_used_at", "admin_id → admin_users.id", "Active login sessions"],
              ["password_reset_tokens", "id, admin_id, token_hash, expires_at", "admin_id → admin_users.id", "Password reset OTP storage"],
              ["bible_verses", "id, text, reference, language, category", "WhatsApp message verses"],
              ["committee_members", "id, name, position, photo, order, is_active", "Church committee listings"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "6.2 Migrations"),
          para("Database schema changes are managed through versioned migration endpoints:"),
          bullet("v9: Added honour_known_as column to donations table"),
          bullet("v10: Added gender column (male/female) to church_members table"),
          bullet("v11: Added phone column to admin_users table"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "6.3 Key Data Flows"),
          para("M-Pesa Donation Flow:", { bold: true }),
          code("1. User submits donation form → POST /api/mpesa/stkpush"),
          code("2. Server creates pending donation record in donations table"),
          code("3. Server calls Safaricom STK Push API → Customer receives M-Pesa prompt on phone"),
          code("4. Customer enters M-Pesa PIN → Safaricom processes payment"),
          code("5. Safaricom calls callback URL → Server updates donation status to 'completed'"),
          code("6. Server generates receipt_number"),
          code("7. If linked to pledge: update pledge.paid + pledge.remaining"),
          code("8. Server sends WhatsApp confirmation via Meta Cloud API"),
          code("9. Server enqueues 5-minute follow-up message"),
          spacer(),
          para("Pledge & WhatsApp Flow:", { bold: true }),
          code("1. User submits pledge → POST /api/pledges"),
          code("2. Server creates/updates pledge record"),
          code("3. Server sends WhatsApp confirmation message"),
          code("4. Server enqueues 3-day follow-up (via BullMQ)"),
          code("5. After 3 days: BullMQ worker sends follow-up WhatsApp with Bible verse"),
          code("6. If payment received: enqueue 5-minute thank-you follow-up"),
          spacer(),
          para("Password Reset Flow:", { bold: true }),
          code("1. User enters email on /admin/forgot-password → POST /api/auth/forgot-password"),
          code("2. Server validates email exists + role is super_admin"),
          code("3. Server generates 6-digit code, stores SHA-256 hash in password_reset_tokens"),
          code("4. Server sends code via WhatsApp (Meta Cloud API) or SMS (Africa's Talking)"),
          code("5. User enters code on /admin/reset-password → POST /api/auth/reset-password"),
          code("6. Server verifies SHA-256 hash, checks expiration (1 hour)"),
          code("7. Server updates password hash, invalidates all existing sessions"),
          code("8. User logs in with new password"),
        ],
      },
      {
        // ── 7. Auth & Auth ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "7. Authentication & Authorization"),
          para("The system implements a comprehensive auth system with JWT tokens, session management, role-based access control, and account lockout protection."),
          spacer(),
          heading(HeadingLevel.HEADING_2, "7.1 Authentication Flow"),
          code("User → Login Form → POST /api/auth/login"),
          code("                         │"),
          code("                         ▼"),
          code("               Validate email + password (bcrypt.compareSync)"),
          code("                         │"),
          code("                ┌────────┴────────┐"),
          code("                ▼                 ▼"),
          code("             Valid?           Invalid?"),
          code("                │                 │"),
          code("        ┌───────┴───────┐         ▼"),
          code("        ▼               ▼    Record failed attempt"),
          code("   Create session    Return   │"),
          code("   + Sign JWT        token    ├─ 5 fails? → Lock 15 min"),
          code("        │                    └─ Return 401"),
          code("        ▼"),
          code("  Return { token, admin }"),
          code("        │"),
          code("        ▼"),
          code("  Client stores token in localStorage"),
          code("        │"),
          code("        ▼"),
          code("  All requests: Authorization: Bearer <token>"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "7.2 Role-Based Access Control"),
          spacer(),
          makeTable(
            ["Role", "Permissions", "Can View", "Can Edit"],
            [
              ["super_admin", "Full system access", "All data including audit logs, admin management, sensitive financial data", "All resources including admin accounts, password reset, system settings"],
              ["admin", "Operational management", "All member/donation/pledge data, analytics, fellowship reports (phone numbers visible)", "Members, donations, pledges, committee, campaigns (not admin accounts or audit)"],
              ["viewer", "Read-only reporting", "Completed donations only (phone numbers masked, receipt numbers hidden), member lists, pledges, analytics", "Nothing — read-only access"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "7.3 Session Management"),
          bullet("On login: JWT signed + session record created in admin_sessions table (SHA-256 hashed token)"),
          bullet("On logout: Session record deleted from table"),
          bullet("On password change: All sessions for that admin deleted (force re-login)"),
          bullet("On password reset: All sessions invalidated after code verification"),
          bullet("Session listing: Super admins can view and revoke all active sessions from Security modal"),
          bullet("Token expiry: 24 hours (configurable via JWT_EXPIRES env var)"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "7.4 Password Policy"),
          bullet("Minimum 8 characters"),
          bullet("At least 1 uppercase letter"),
          bullet("At least 1 number"),
          bullet("bcrypt hash with 10 salt rounds"),
          bullet("Rate-limited: max 5 attempts per 15-minute window per email"),
          bullet("Account lockout: 15 minutes after 5 consecutive failures"),
          bullet("Failed attempts reset on successful login"),
          bullet("No password or email persistence on login form (autocomplete='off' on all fields)"),
        ],
      },
      {
        // ── 8. Security ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "8. Security Architecture"),
          heading(HeadingLevel.HEADING_2, "8.1 Encryption At Rest"),
          makeTable(
            ["Data Type", "Encryption Method", "Notes"],
            [
              ["Passwords", "bcrypt (10 rounds)", "Salt auto-generated per password, Original password never stored"],
              ["JWT Tokens", "HS256", "Signed with JWT_SECRET environment variable"],
              ["Session Tokens", "SHA-256", "Hashed before database storage; original token never persisted"],
              ["Reset Tokens", "SHA-256", "6-digit code hashed before DB storage; plaintext never logged"],
              ["Database", "Supabase Managed", "Encrypted at rest by default (AES-256)"],
              ["Environment Secrets", "Vercel Encrypted", "All API keys, tokens, and secrets stored encrypted in Vercel"],
              ["HTTPS Traffic", "TLS 1.3", "Terminated at Cloudflare edge, re-encrypted to Vercel origin"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "8.2 Data Isolation & Masking"),
          para("Viewer Role Data Masking:", { bold: true }),
          code("// donations.ts - Viewer sees completed donations only"),
          code("if (!admin || admin.role === 'viewer') {"),
          code("  query = query.eq('status', 'completed');"),
          code("}"),
          code(""),
          code("// Phone number masking for non-super_admin"),
          code("if (admin.role !== 'super_admin') {"),
          code("  donation.phone = phone.slice(0, 6) + '****';  // e.g. '072727****'"),
          code("  delete donation.receipt_number;  // Receipt hidden"),
          code("}"),
          code(""),
          code("// PersonalPortfolio - M-Pesa receipt codes hidden from donors"),
          code("if (!admin) delete donation.receipt_number;"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "8.3 Rate Limiting"),
          makeTable(
            ["Layer", "Limit", "Scope"],
            [
              ["Global API", "300 requests/minute", "Per IP address (sliding window)"],
              ["Login Attempts", "5 attempts/15 minutes", "Per email address (persistent counter)"],
              ["Password Reset", "Implicit (token-based)", "Per email, token expires in 1 hour"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "8.4 Secure Password Reset Design"),
          para("The password reset flow was designed with maximum security in mind:"),
          bullet("Restricted to super_admin role only (admins and viewers cannot reset)"),
          bullet("Reset code sent via WhatsApp (Meta Cloud API) or SMS (Africa's Talking) — never displayed on screen"),
          bullet("Code is 6-digit numeric, stored as SHA-256 hash in database"),
          bullet("Code expires after 1 hour"),
          bullet("Previous tokens invalidated when new one is generated"),
          bullet("On successful reset: all sessions invalidated (user must re-login everywhere)"),
          bullet("Password strength enforced: 8+ chars, 1 uppercase, 1 number"),
        ],
      },
      {
        // ── 9. Integrations ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "9. Integration Architecture"),
          heading(HeadingLevel.HEADING_2, "9.1 M-Pesa Daraja API (Safaricom)"),
          para("M-Pesa is the primary payment method. The system implements two flows:"),
          bullet("STK Push (Server-initiated): Customer enters phone + amount → server calls Safaricom STK Push API → Customer receives M-Pesa prompt on their phone"),
          bullet("C2B (Customer-initiated): Customer sends M-Pesa to paybill 835872 → Safaricom calls validation URL → Server validates → Safaricom calls confirmation URL → Server records donation"),
          para("Security measures:", { bold: true }),
          bullet("All callbacks validated against expected payload structure"),
          bullet("Transaction amounts verified server-side to prevent tampering"),
          bullet("Duplicate transaction detection via checkout_request_id"),
          bullet("No M-Pesa credentials (consumer key/secret/passkey) exposed to client"),
          bullet("C2B URLs must be re-registered if serverless function URL changes"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "9.2 Meta Cloud API (WhatsApp)"),
          para("WhatsApp messaging for pledge confirmations, payment receipts, reminders, and password reset codes."),
          bullet("API: graph.facebook.com/v21.0/{phone-number-id}/messages"),
          bullet("Authentication: Long-lived access token (Bearer)"),
          bullet("Message types: Free-form text for user-initiated conversations; authentication templates for password reset"),
          bullet("Replaced Twilio (deprecated) on June 23, 2026"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "9.3 Africa's Talking (SMS)"),
          para("SMS for password reset OTP delivery as a fallback channel."),
          bullet("SDK: africastalking npm package"),
          bullet("Phone number format: International (E.164), auto-normalized"),
          bullet("Status: Sandbox mode requiring funded account and Live switch for production"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "9.4 LibreTranslate (Self-Hosted)"),
          para("Free, self-hosted translation service for auto-translating English site content to Swahili on save."),
          bullet("No API key required"),
          bullet("Runs as a separate service (not on Vercel)"),
          bullet("Translates: About section, Harambee reason, and 3 card titles/texts"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "9.5 Redis (Upstash)"),
          para("Serverless Redis for two purposes:"),
          bullet("BullMQ Queue: Background job processing (reminders, follow-ups, M-Pesa polling, analytics refresh)"),
          bullet("Cache: Response caching for frequently accessed data (analytics KPIs, fellowship progress)"),
        ],
      },
      {
        // ── 10. Queue ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "10. Queue & Background Jobs"),
          para("BullMQ with Upstash Redis manages all asynchronous background processing. On Vercel (serverless mode), workers are started via a keep-alive mechanism. In local development, workers run in-process."),
          spacer(),
          makeTable(
            ["Queue Name", "Job Type", "Delay", "Retries", "Description"],
            [
              ["reminders", "send_reminder", "None (immediate)", "3 (exponential backoff)", "Send pledge reminder via WhatsApp with Bible verses"],
              ["follow-up", "send_follow_up", "3 days (pledge) / 5 min (payment)", "3 (exponential backoff)", "Follow-up message checking on pledge or thanking for payment"],
              ["mpesa", "poll_mpesa_status", "15 seconds initial", "5 (exponential backoff)", "Poll M-Pesa STK Push status until completed/timed out"],
              ["exports", "generate_pdf / generate_ppt", "None", "2 (fixed delay)", "Generate PDF/PPT export reports"],
              ["audit", "batch_audit_write", "None", "3", "Batch audit log writes to reduce DB writes"],
              ["analytics-refresh", "refresh_analytics_cache", "5 seconds", "None", "Refresh cached analytics KPIs after data mutation"],
            ],
          ),
          spacer(),
          para("Worker initialization: In serverless (Vercel), workers are started when the function boots but may be terminated after inactivity. In non-serverless mode (local dev), workers run persistently via startAllWorkers()."),
        ],
      },
      {
        // ── 11. Deployment ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "11. Deployment Architecture"),
          para("The application is hosted entirely on Vercel's platform with the following configuration:"),
          spacer(),
          makeTable(
            ["Component", "Hosting", "Configuration"],
            [
              ["Static assets (SPA)", "Vercel Edge Network", "Built by Vite → output in dist/ → served globally via CDN"],
              ["API (Express)", "Vercel Serverless Functions", "api/index.ts → server/index.ts → 30s timeout, 1024MB memory"],
              ["Database", "Supabase (Managed PostgreSQL)", "Project ref: ktyfkzyigauhwqgfpjsc, Region: US East"],
              ["Cache/Queue", "Upstash Redis", "Serverless Redis with TLS, auto-scaling to zero"],
              ["Domain", "Vercel DNS", "aipcaharambee.com (custom domain)"],
              ["SSL", "Cloudflare + Vercel", "TLS 1.3, automatic certificate management"],
              ["Version Control", "GitHub Private", "Automatic deployments on git push to main branch"],
            ],
          ),
          spacer(),
          para("Build & Deploy Pipeline:", { bold: true }),
          code("1. Developer pushes to GitHub main branch"),
          code("2. Vercel detects change → triggers build"),
          code("3. Build step: npm install → vite build (client) → TypeScript compile (server)"),
          code("4. Serverless function bundle created with dependencies"),
          code("5. Static assets deployed to CDN edge"),
          code("6. Serverless function deployed to Washington, D.C. (iad1)"),
          code("7. Build cache stored for subsequent deployments"),
          code("8. Production URL updated: https://aipcaharambee.com"),
          spacer(),
          para("Environment Variables (configured in Vercel):", { bold: true }),
          makeTable(
            ["Variable", "Purpose", "Sensitive"],
            [
              ["NEXT_PUBLIC_SUPABASE_URL", "Supabase project URL", "No"],
              ["NEXT_PUBLIC_SUPABASE_ANON_KEY", "Public anon key", "No"],
              ["SUPABASE_SERVICE_ROLE_KEY", "Service role key (full DB access)", "Yes"],
              ["JWT_SECRET", "Token signing secret", "Yes"],
              ["META_WHATSAPP_TOKEN", "Meta Cloud API access token", "Yes"],
              ["META_PHONE_NUMBER_ID", "WhatsApp Business phone number ID", "Yes"],
              ["AT_API_KEY", "Africa's Talking API key", "Yes"],
              ["AT_USERNAME", "Africa's Talking account username", "Yes"],
              ["MPESA_CONSUMER_KEY", "Daraja API consumer key", "Yes"],
              ["MPESA_CONSUMER_SECRET", "Daraja API consumer secret", "Yes"],
              ["MPESA_PASSKEY", "STK Push passkey", "Yes"],
              ["MPESA_SHORTCODE", "Paybill number (835872)", "No"],
              ["MPESA_CALLBACK_URL", "C2B callback endpoint URL", "No"],
              ["MPESA_ENV", "sandbox or production", "No"],
              ["REDIS_URL / KV_URL", "Upstash Redis connection string", "Yes"],
              ["NEXT_PUBLIC_BASE_URL", "Public site URL", "No"],
              ["CORS_ORIGIN", "Allowed CORS origin", "No"],
            ],
          ),
        ],
      },
      {
        // ── 12. Monitoring & Audit ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "12. Monitoring & Audit"),
          heading(HeadingLevel.HEADING_2, "12.1 Audit Logging"),
          para("All admin actions are logged to the audit_logs table. The log entry captures actor, action, resource, timestamp, IP, and user agent. Logs are marked immutable to prevent tampering."),
          spacer(),
          para("Audit Log Schema:", { bold: true }),
          code("interface AuditLog {"),
          code("  id: string;           // UUID"),
          code("  timestamp: string;    // ISO 8601"),
          code("  actor_id: string;     // admin_users.id"),
          code("  actor_name: string;   // Admin's display name"),
          code("  actor_role: string;   // super_admin | admin | viewer"),
          code("  action: string;       // e.g. 'login', 'create_member', 'delete_pledge'"),
          code("  resource_type: string | null;"),
          code("  resource_id: string | null;"),
          code("  details: object | null;"),
          code("  ip_address: string | null;"),
          code("  user_agent: string | null;"),
          code("  request_id: string;   // Correlates with server request"),
          code("  immutable: boolean;   // Always true"),
          code("}"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "12.2 Monitored Actions"),
          makeTable(
            ["Category", "Actions Logged"],
            [
              ["Authentication", "login, logout, failed_login, password_reset, password_reset_request, setup_complete"],
              ["Members", "create_member, update_member, delete_member, bulk_create, bulk_edit, bulk_delete, dedup"],
              ["Donations", "create_donation, update_donation, delete_donation, status_update"],
              ["Pledges", "create_pledge, update_pledge, delete_pledge, payment, adjustment"],
              ["Admin Management", "create_admin, update_admin, delete_admin, change_password, revoke_session"],
              ["Security", "view_audit_logs, view_sensitive_data"],
              ["Settings", "update_settings"],
              ["Migration", "migrate_v9, migrate_v10"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "12.3 Debugging & Observability"),
          bullet("Server logs: Vercel function logs accessible via Vercel Dashboard or CLI"),
          bullet("Request ID: Every request tagged with UUID for log correlation"),
          bullet("Client console: All API error messages shown in UI via Toast/Alert components"),
          bullet("Audit viewer: Super admins can browse audit logs at bottom of Overview tab in Admin Dashboard"),
        ],
      },
      {
        // ── 13. Incident Response ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "13. Incident Response & Recovery"),
          heading(HeadingLevel.HEADING_2, "13.1 Detecting Incidents"),
          bullet("Audit logs show all admin actions with timestamps and IP addresses"),
          bullet("Failed login attempts recorded with email and IP address"),
          bullet("Rate limit breaches trigger 429 responses indicating possible brute-force attempts"),
          bullet("All API errors logged server-side with request IDs"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "13.2 Responding to Incidents"),
          makeTable(
            ["Incident", "Response Procedure"],
            [
              ["Compromised admin account", "Super admin resets password via /admin/reset-password; all sessions invalidated automatically"],
              ["Suspicious activity", "Review audit logs filtered by affected admin_id; check IP addresses and timestamps"],
              ["Brute force attack", "Rate limiting blocks excessive attempts; monitor failed_login audit entries"],
              ["Database breach", "Immediately rotate SUPABASE_SERVICE_ROLE_KEY in Vercel env vars"],
              ["M-Pesa discrepancy", "Cross-reference donation records with Safaricom M-Pesa statement"],
              ["WhatsApp API failure", "Check Meta access token expiry; regenerate token from Meta Business Settings"],
              ["Serverless function crash", "Cold start resolves automatically; check Vercel function logs for stack trace"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "13.3 Recovery Procedures"),
          bullet("Lost JWT_SECRET: Generate new secret → all existing tokens become invalid → all admins must re-login"),
          bullet("Lost Supabase access: Contact Supabase support with project ref: ktyfkzyigauhwqgfpjsc"),
          bullet("M-Pesa integration failure: Re-register C2B URLs from Admin Dashboard or reset via Safaricom portal"),
          bullet("Lost Meta access token: Regenerate from Meta Business Settings → System Settings → WhatsApp Business Account → API"),
          bullet("Database corruption: Restore from Supabase point-in-time recovery (PITR) — contact Supabase support"),
        ],
      },
      {
        // ── 14. Appendices ──
        properties: {
          page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } },
        },
        children: [
          heading(HeadingLevel.HEADING_1, "14. Appendices"),
          heading(HeadingLevel.HEADING_2, "Appendix A: Complete File Map"),
          spacer(),
          code("church/"),
          code("├── api/"),
          code("│   └── index.ts                 # Vercel serverless function entry point"),
          code("├── src/                         # Frontend"),
          code("│   ├── main.tsx                 # React DOM entry"),
          code("│   ├── App.tsx                  # Router + layout"),
          code("│   ├── index.css                # Tailwind + custom styles (nobuk #08428c)"),
          code("│   ├── pages/"),
          code("│   │   ├── HomePage.tsx          # Public landing page"),
          code("│   │   ├── AdminLogin.tsx        # Login form"),
          code("│   │   ├── AdminSetup.tsx        # First-time super admin setup"),
          code("│   │   ├── AdminDashboard.tsx    # Full admin panel (2800+ lines)"),
          code("│   │   ├── ForgotPassword.tsx    # Password reset request"),
          code("│   │   ├── ResetPassword.tsx     # Code entry + new password"),
          code("│   │   └── JackPortfolio.tsx     # Personal portfolio page"),
          code("│   ├── components/"),
          code("│   │   ├── ChurchHero.tsx        # Banner section"),
          code("│   │   ├── SlideshowBackground.tsx"),
          code("│   │   ├── LiveProgress.tsx      # Real-time progress bar"),
          code("│   │   ├── FellowshipProgress.tsx"),
          code("│   │   ├── PledgeBoard.tsx       # Pledge leaderboard"),
          code("│   │   ├── AboutSection.tsx      # Church mission"),
          code("│   │   ├── ContributeSection.tsx"),
          code("│   │   ├── DonationModal.tsx     # Donation form modal"),
          code("│   │   ├── DonationForm.tsx"),
          code("│   │   ├── Footer.tsx            # Site footer"),
          code("│   │   └── jack/JackRouter.tsx"),
          code("│   ├── context/LanguageContext.tsx"),
          code("│   ├── hooks/useInView.ts"),
          code("│   └── lib/                     # Client utilities"),
          code("├── server/                      # Backend"),
          code("│   ├── index.ts                 # Express app + middleware stack"),
          code("│   ├── routes/                  # 18 route modules"),
          code("│   │   ├── auth.ts              # Auth + password reset"),
          code("│   │   ├── admin.ts             # Admin CRUD + stats"),
          code("│   │   ├── members.ts           # Member CRUD + bulk ops"),
          code("│   │   ├── donations.ts         # Donation CRUD"),
          code("│   │   ├── pledges.ts           # Pledge CRUD + pay"),
          code("│   │   ├── mpesa.ts             # M-Pesa integration"),
          code("│   │   ├── c2b.ts              # C2B callbacks"),
          code("│   │   ├── analytics.ts         # Dashboard analytics"),
          code("│   │   ├── settings.ts          # Site settings"),
          code("│   │   ├── fellowships.ts       # Fellowship progress"),
          code("│   │   ├── contributions.ts     # Excel/PDF export"),
          code("│   │   ├── reminders.ts         # Send reminders"),
          code("│   │   ├── committee.ts         # Committee management"),
          code("│   │   ├── councils.ts          # Council management"),
          code("│   │   ├── campaigns.ts         # Campaign management"),
          code("│   │   ├── ledger.ts            # Financial ledger"),
          code("│   │   ├── translate.ts         # Translation proxy"),
          code("│   │   └── verses.ts            # Bible verses"),
          code("│   └── lib/                     # 8 library modules"),
          code("│       ├── admin.ts             # Auth + middleware + audit"),
          code("│       ├── supabase.ts          # DB client"),
          code("│       ├── meta-whatsapp.ts     # Meta WhatsApp"),
          code("│       ├── africastalking.ts    # AT SMS"),
          code("│       ├── redis.ts             # Redis cache"),
          code("│       ├── queue.ts             # BullMQ workers"),
          code("│       ├── permissions.ts       # RBAC matrix"),
          code("│       └── audit.ts             # Audit logging"),
          code("├── supabase/                    # SQL migrations"),
          code("├── docs/                        # Documentation"),
          code("├── public/images/               # Static assets"),
          code("├── vercel.json                  # Vercel configuration"),
          code("└── package.json"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "Appendix B: Vercel Configuration"),
          spacer(),
          code("// vercel.json"),
          code("{"),
          code('  "framework": null,'),
          code('  "buildCommand": "vite build",'),
          code('  "outputDirectory": "dist",'),
          code('  "installCommand": "npm install",'),
          code('  "functions": {'),
          code('    "api/index.ts": {'),
          code('      "maxDuration": 30,'),
          code('      "memory": 1024'),
          code("    }"),
          code("  },"),
          code('  "rewrites": ['),
          code('    { "source": "/api/(.*)", "destination": "/api" },'),
          code('    { "source": "/((?!api/).*)", "destination": "/index.html" }'),
          code("  ]"),
          code("}"),
          spacer(),
          heading(HeadingLevel.HEADING_2, "Appendix C: Key Security Recommendations (Next Phase)"),
          spacer(),
          makeTable(
            ["Priority", "Recommendation", "Effort", "Impact"],
            [
              ["High", "Add 2FA (TOTP) for super_admin accounts", "2-3 days", "Prevents account takeover even if password is compromised"],
              ["High", "Move auth token from localStorage to httpOnly cookie", "2 days", "Eliminates XSS token theft risk"],
              ["High", "Add IP whitelist for admin dashboard", "1 day", "Restricts admin access to church/staff IPs"],
              ["Medium", "Database backup automation", "0.5 day", "Point-in-time recovery capability"],
              ["Medium", "Rate limit for password reset endpoint", "0.5 day", "Prevents OTP brute force"],
              ["Low", "Web Application Firewall (WAF)", "Vendor setup", "Additional DDoS and OWASP protection"],
              ["Low", "Regular penetration testing", "Quarterly", "Identifies unknown vulnerabilities"],
              ["Low", "Automated security scanning in CI/CD", "1 day", "Catches dependency vulnerabilities pre-deployment"],
            ],
          ),
          spacer(),
          heading(HeadingLevel.HEADING_2, "Appendix D: Project Critical Context"),
          spacer(),
          para("Supabase Project Ref: ktyfkzyigauhwqgfpjsc", { bold: true }),
          para("Vercel Project ID: prj_AWIWtnSaQDHBLJWF227eXBQ68LBy", { bold: true }),
          para("Vercel Team ID: team_Ow3y8XX6KqSFMox8UJx3zfuA", { bold: true }),
          para("Custom Domain: https://aipcaharambee.com", { bold: true }),
          para("M-Pesa Paybill: 835872 (AIPCA Harambee)", { bold: true }),
          para("M-Pesa Environment: Production", { bold: true }),
          para("Repo: github.com/JaynneWangeci/church (Private)", { bold: true }),
          para("Fellowships: 11 (Maranatha, Bethlehem, Jerusalem, Aefeso, Galilee, Bethel, Berea, Judea, Jordan, Bethany, General Member)", { bold: true }),
          para("Fundraising Goal: KES 30,000,000", { bold: true }),
          para("Church Phone: +254 727 278 577", { bold: true }),
          spacer(),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
            border: { top: { style: BorderStyle.SINGLE, size: 6, color: BLUE, space: 1 } },
            children: [
              new TextRun({ text: "End of Document", font: "Calibri", size: 20, color: MUTED, italics: true }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 200 },
            children: [
              new TextRun({ text: "AIPCA Bahati Cathedral — Harambee Development Fund", font: "Calibri", size: 18, color: MUTED }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: "Document generated June 2026 | Next review: September 2026", font: "Calibri", size: 18, color: MUTED }),
            ],
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync("docs/AIPCA_System_Architecture.docx", buffer);
  console.log("✅ Generated: docs/AIPCA_System_Architecture.docx");
}

main().catch(console.error);
